services:
  terve:
    image: lehmann314159/terve:latest
    container_name: terve
    volumes:
      - terve-data:/app/data
    environment:
      - PORT=3333
      - DATABASE_PATH=/app/data/terve.db
    restart: unless-stopped
    networks:
      - web

volumes:
  terve-data:

networks:
  web:
    external: true